backend:
  name: github
  repo: Tungetyt/accounting-website
media_folder: static/assets
public_folder: /assets
collections:
  - name: home
    label: home
    folder: home
    create: true
    fields:
      - label: "titleNames"
        name: "titleNames"
        widget: "list"
        field: { label: name, name: name, widget: string }
      - { label: place, name: place, widget: string }
      - { label: "landingPageImage"
            name: "landingPageImage"
            widget: "image" }
  - name: miscellaneous
      label: miscellaneous
      folder: miscellaneous
      create: true
      fields:
        - { label: "langBtn"
              name: "langBtn"
              widget: "string" }
        - { label: "themeBtn"
              name: "themeBtn"
              widget: "string" }
        - { label: "themeBtn"
              name: "themeBtn"
              widget: "string" }
  - name: navigation
      label: navigation
      folder: navigation
      create: true
      fields:
        - { label: "home"
              name: "home"
              widget: "string" }
        - { label: "services"
              name: "services"
              widget: "string" }
        - { label: "prices"
              name: "prices"
              widget: "string" }
        - { label: "about"
              name: "about"
              widget: "string" }
        - { label: "faq"
              name: "faq"
              widget: "string" }
        - { label: "contact"
              name: "contact"
              widget: "string" }
