backend:
  # name: github
  # repo: Tungetyt/accounting-website
  name: git-gateway

# when using the default proxy server port, npx netlify-cms-proxy-server
local_backend: true

media_folder: static/assets
public_folder: /assets
collections:
  - name: images
    label: images
    folder: images
    create: true
    fields:
      - label: "title"
        name: "title"
        widget: "string"
      - label: "landingPageImage"
        name: "landingPageImage"
        widget: "image"
        required: false
      - label: "AccountingImage"
        name: "AccountingImage"
        widget: "image"
        required: false
      - label: "Accounting2Image"
        name: "Accounting2Image"
        widget: "image"
        required: false
      - label: "hrImage"
        name: "hrImage"
        widget: "image"
        required: false
      - label: "hr2Image"
        name: "hr2Image"
        widget: "image"
        required: false
      - label: "taxesImage"
        name: "taxesImage"
        widget: "image"
        required: false
      - label: "taxes2Image"
        name: "taxes2Image"
        widget: "image"
        required: false
      - label: "legalImage"
        name: "legalImage"
        widget: "image"
        required: false
      - label: "legal2Image"
        name: "legal2Image"
        widget: "image"
        required: false
      - label: "financeImage"
        name: "financeImage"
        widget: "image"
        required: false
      - label: "finance2Image"
        name: "finance2Image"
        widget: "image"
        required: false
      - label: "businessImage"
        name: "businessImage"
        widget: "image"
        required: false
      - label: "business2Image"
        name: "business2Image"
        widget: "image"
        required: false
      - label: "officeImage"
        name: "officeImage"
        widget: "image"
        required: false  
  - name: vavicom
    label: vavicom
    folder: vavicom
    create: true
    fields:
      - label: "title"
        name: "title"
        widget: "string"  
      - label: "landing"
        name: "landing"
        widget: "list"
        required: false
        collapsed: false
        field: {label: "titlePart", name: "titlePart", widget: "string", required: false}
      - label: "address"
        name: "address"
        widget: "string"
        required: false
      - label: "langBtn"
        name: "langBtn"
        widget: "string"
        required: false
      - label: "themeBtn"
        name: "themeBtn"
        widget: "string"
        required: false
      - label: "backToTopBtn"
        name: "backToTopBtn"
        widget: "string"
        required: false
      - label: "home"
        name: "home"
        widget: "string"
        required: false
      - label: "services"
        name: "services"
        widget: "string"
        required: false
      - label: "prices"
        name: "prices"
        widget: "string"
        required: false
      - label: "about"
        name: "about"
        widget: "string"
        required: false
      - label: "faq"
        name: "faq"
        widget: "string"
        required: false
      - label: "contact"
        name: "contact"
        widget: "string"
        required: false
      - label: "notfound"
        name: "notfound"
        widget: "object"
        required: false
        collapsed: false
        fields: 
          - {label: "header", name: "header", widget: "text", required: false}
          - {label: "description", name: "description", widget: "text", required: false}
          - {label: "goback", name: "goback", widget: "text", required: false}
      - label: "hamburger"
        name: "hamburger"
        widget: "string"
        required: false
      - label: "servicesSection"
        name: "servicesSection"
        widget: "object"
        required: false
        collapsed: false
        fields: 
          - {label: "accounting", name: "accounting", widget: "text", required: false}
          - {label: "hrAndPayroll", name: "hrAndPayroll", widget: "text", required: false}
          - {label: "taxServices", name: "taxServices", widget: "text", required: false}
          - {label: "legalServices", name: "legalServices", widget: "text", required: false}
          - {label: "financialServices", name: "financialServices", widget: "text", required: false}
          - {label: "businessServices", name: "businessServices", widget: "text", required: false}
      - label: "accounting"
        name: "accounting"
        widget: "object"
        collapsed: false
        fields: 
          - label: "info"
            name: "info"
            widget: "list"
            collapsed: false
            field: {label: "infoPart", name: "infoPart", widget: "text", required: false}
          - label: "services"
            name: "services"
            widget: "object"
            collapsed: false
            fields: 
              - label: "intro"
                name: "intro"
                widget: "list"
                collapsed: false
                field: {label: "introPart", name: "introPart", widget: "text", required: false}
              - label: "more"
                name: "more"
                widget: "object"
                collapsed: false
                fields: 
                  - label: "moreIntro"
                    name: "moreIntro"
                    widget: "list"
                    collapsed: false
                    field: {label: "moreIntroPart", name: "moreIntroPart", widget: "text", required: false}
                  - label: "next"
                    name: "next"
                    widget: "list"
                    collapsed: false
                    field:  {label: "nextPart", name: "nextPart", widget: "text", required: false}
      - label: "hrAndPayroll"
        name: "hrAndPayroll"
        widget: "object"
        collapsed: false
        fields: 
          - label: "info"
            name: "info"
            widget: "list"
            collapsed: false
            field: {label: "infoPart", name: "infoPart", widget: "text", required: false}
          - label: "services"
            name: "services"
            widget: "list"
            collapsed: false
            field: {label: "servicesPart", name: "servicesPart", widget: "text", required: false}
          - label: "more"
            name: "more"
            widget: "object"
            collapsed: false
            fields: 
              - label: "moreList"
                name: "moreList"
                widget: "list"
                collapsed: false
                field: {label: "moreListPart", name: "moreListPart", widget: "text", required: false}
              - label: "next"
                name: "next"
                widget: "object"
                field: {label: "nextPart", name: "nextPart", widget: "text", required: false}
      - label: "taxServices"
        name: "taxServices"
        widget: "object"
        collapsed: false
        fields: 
          - label: "info"
            name: "info"
            widget: "list"
            collapsed: false
            field: {label: "infoPart", name: "infoPart", widget: "text", required: false}
          - label: "info1"
            name: "info1"
            widget: "list"
            collapsed: false
            field: {label: "info1Part", name: "info1Part", widget: "text", required: false}
          - label: "services"
            name: "services"
            widget: "list"
            collapsed: false
            field: {label: "servicesPart", name: "servicesPart", widget: "text", required: false}
          - label: "more"
            name: "more"
            widget: "object"
            collapsed: false
            fields: 
              - {label: "0", name: "0", widget: "text", required: false}
      - label: "legalServices"
        name: "legalServices"
        widget: "list"
        collapsed: false
        field: {label: "legalServicesPart", name: "legalServicesPart", widget: "text", required: false}
      - label: "financialServices"
        name: "financialServices"
        widget: "list"
        collapsed: false
        fields: 
          - {label: "financialServicesPart", name: "financialServicesPart", widget: "text", required: false}
      - label: "businessServices"
        name: "businessServices"
        widget: "list"
        collapsed: false
        field: {label: "businessServicesPart", name: "businessServicesPart", widget: "text", required: false}
      - label: "pricesSection"
        name: "pricesSection"
        widget: "object"
        collapsed: false
        fields: 
          - label: "offers"
            name: "offers"
            widget: "list"
            collapsed: false
            field: {label: offer, name: offer, widget: text, required: false}
          - label: "prices"
            name: "prices"
            widget: "list"
            collapsed: false
            field: {label: price, name: price, widget: text, required: false}
          - label: "specialOffer"
            name: "specialOffer"
            widget: "list"
            collapsed: false
            field: {label: offer, name: offer, widget: text, required: false}
          - label: "dataTable"
            name: "dataTable"
            widget: "list"
            collapsed: false
            field: {label: offer, name: offer, widget: text, required: false}
      - label: "aboutBtn"
        name: "aboutBtn"
        widget: "list"
        collapsed: false
        field: {label: "aboutBtnPart", name: "aboutBtnPart", widget: "text", required: false}
      - label: "clientValueBtn"
        name: "clientValueBtn"
        widget: "list"
        collapsed: false
        field: {label: "clientValueBtnPart", name: "clientValueBtnPart", widget: "text", required: false}
      - label: "whyCooperateBtn"
        name: "whyCooperateBtn"
        widget: "list"
        collapsed: false
        field: {label: "whyCooperateBtnPart", name: "whyCooperateBtnPart", widget: "text", required: false}
      - label: "whatDifferBtn"
        name: "whatDifferBtn"
        widget: "list"
        collapsed: false
        field: {label: "whatDifferBtnPart", name: "whatDifferBtnPart", widget: "text", required: false}
      - label: "getToKnowUsBtn"
        name: "getToKnowUsBtn"
        widget: "list"
        collapsed: false
        field: {label: "getToKnowUsBtnPart", name: "getToKnowUsBtnPart", widget: "text", required: false}
      - label: "workTogetherBtn"
        name: "workTogetherBtn"
        widget: "list"
        collapsed: false
        field: {label: "workTogetherBtnPart", name: "workTogetherBtnPart", widget: "text", required: false}
      - label: "safetyBtn"
        name: "safetyBtn"
        widget: "list"
        collapsed: false
        field: {label: "safetyBtnPart", name: "safetyBtnPart", widget: "text", required: false}
      - label: "ourClientsBtn"
        name: "ourClientsBtn"
        widget: "list"
        collapsed: false
        field: {label: "ourClientsBtnPart", name: "ourClientsBtnPart", widget: "text", required: false}
      - label: "faqSection"
        name: "faqSection"
        widget: "list"
        collapsed: false
        fields: 
          - {label: "q", name: "q", widget: "text", required: false}
          - {label: "a", name: "a", widget: "text", required: false}
      - label: "contactSection"
        name: "contactSection"
        widget: "object"
        collapsed: false
        fields: 
          - {label: "name", name: "name", widget: "string", required: false}
          - {label: "street", name: "street", widget: "string", required: false}
          - {label: "street2", name: "street2", widget: "string", required: false}
          - {label: "town", name: "town", widget: "string", required: false}
          - {label: "town2", name: "town2", widget: "string", required: false}
          - {label: "phone", name: "phone", widget: "string", required: false}
          - {label: "email", name: "email", widget: "string", required: false}
          - {label: "ourOffice", name: "ourOffice", widget: "string", required: false}
          - {label: "whereAreWe", name: "whereAreWe", widget: "string", required: false}
